version: '3.1'

services:
  wordpress:
    image: wordpress:4.9.7
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_DISPLAY', false);
    depends_on:
      - mysql
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  formatter:
    build:
      dockerfile: Dockerfile.php-cs-fixer
      context: ./plugins/panegyric
    volumes:
      - ./plugins/panegyric:/app